### ISSUE TITLE
Exception = Out of range Address

### ISSUE THREAD

**Issue by KaiserSozo** [altimesh/hybridizer-basic-samples#42] opened 2018-03-19 08:50 UTC
I have following function beginning:
[EntryPoint]
        public static void ComputeKohonen(float[] plainNetwork, float[] learningExamples, int[] winRates, int xDim, int yDim, int examplesCount, int minWinRate, float error, float fairnessRatio, float learningVelocity)
        {
            System.Threading.Tasks.Parallel.For(0, examplesCount, (i) =>
            {
                float[] output = new float[xDim];

                for (int j = 0; j < xDim; j +=1)
                {  ....

And at j = 64 I get Exception = Out of range Address. 
is it a bug or I do not understand something?

**Comment by JeWaVe** [comment] 2018-03-19 08:55
Thanks for reporting this issue. 

Nested Parallel.For is not supported. This is likely related. 

In an entryPoint, the outer parallel for will map to a CUDA-grid. Adding another level of parallelism would require us to implement [dynamic parallelism](https://devblogs.nvidia.com/cuda-dynamic-parallelism-api-principles/), which has a huge performance cost

**Comment by KaiserSozo** [comment] 2018-03-19 08:58
So cycle  for (int j = 0; j < xDim; j +=1) also executes in parallel? I want it to execute consequentially.

**Comment by JeWaVe** [comment] 2018-03-19 08:59
No this loop is not parallel. I thought the exception came when the commented line was uncommented

**Comment by JeWaVe** [comment] 2018-03-19 09:09
Can you extract a reproducer I can run on my side?

**Comment by KaiserSozo** [comment] 2018-03-19 09:27
Do you need full code?

**Comment by JeWaVe** [comment] 2018-03-19 09:30
Can you extract just the buggy part? Something like that : https://stackoverflow.com/help/mcve

**Comment by KaiserSozo** [comment] 2018-03-19 09:42
[EntryPoint]
        public static void ComputeKohonen(float[] plainNetwork, float[] learningExamples, int[] winRates, int xDim, int yDim, 
                                    int examplesCount, int minWinRate, float error, float fairnessRatio, float learningVelocity)
        {
            System.Threading.Tasks.Parallel.For(0, examplesCount, (i) =>
            //for (int i = 0; i < examplesCount; ++i)
            //for (int i = blockDim.x * blockIdx.x + threadIdx.x; i < examplesCount; i += blockDim.x * gridDim.x)
            {
                float[] output = new float[xDim];

                //System.Threading.Tasks.Parallel.For(0, xDim, (j) =>
                for (int j = 0; j < xDim; j +=1)
                {
                    float sum = 0.0f;

                    for (int k = 0; k < yDim; ++k)
                    {
                        float difDist = plainNetwork[j * yDim + k] - learningExamples[i * yDim + k];
                        sum += difDist * difDist;
                    }

                    output[j] = sqrtf(sum);
                }
            });
        }

**Comment by KaiserSozo** [comment] 2018-03-19 09:45
So plainNetwork is 5000*200 volume. learningExamples is 100 000 * 200 volume.

**Comment by KaiserSozo** [comment] 2018-03-19 09:47
Btw, can I pass double dimensioned arrays? Like that float[][] plainNetwork. I tried and thought that problem was in that. But...

**Comment by KaiserSozo** [comment] 2018-03-19 09:53
And also I searched information about synchronization, but haven't found it yet. I'm reading info from float[] plainNetwork and storing results there too and also incrementing values from int[] winRates. Do I need synchronize it manually. If yes then how better should I do it?

**Comment by JeWaVe** [comment] 2018-03-19 10:37
```
class Program
    {
        [EntryPoint]
        public static void ComputeKohonen(float[] plainNetwork, float[] learningExamples, int xDim, int yDim, int examplesCount)
        {
            Parallel.For(0, examplesCount, (i) =>
            {
                float[] output = new float[xDim];
                
                for (int j = 0; j < xDim; j += 1)
                {
                    float sum = 0.0f;

                    for (int k = 0; k < yDim; ++k)
                    {
                        float difDist = plainNetwork[j * yDim + k] - learningExamples[i * yDim + k];
                        sum += difDist * difDist;
                    }

                    output[j] = (float) Math.Sqrt(sum);
                }
            });
        }


        static void Main(string[] args)
        {
            int xdim = 32, ydim = 32;
            int examplesCount = 1024;

            // inferred from usage
            var plain = new float[xdim * ydim + ydim];
            var learning = new float[examplesCount * ydim + ydim];
            // first run in plain C# to verify
            ComputeKohonen(plain, learning, xdim, ydim, examplesCount);
            // run the cuda version
            HybRunner.Cuda("HybridizerSample11_CUDA.dll").Wrap(new Program()).ComputeKohonen(plain, learning, xdim, ydim, examplesCount);
        }
    }
```
From the above code sample, I cannot reproduce your issue. 
Do you allocate enough memory? 
Does the issue reproduce in plain C# without hybridizer? 

About double dimensioned arrays, you need support for HybArrays, which are not officially supported in Essentials. 

However you can try playing with Hybridizer Options in the generated native project.

**Comment by KaiserSozo** [comment] 2018-03-19 10:54
Let me try. Could please also answer about synchronization, I've asked earlier in this thread?

**Comment by KaiserSozo** [comment] 2018-03-19 11:02
in plain C# code works fine.
I see you allocated memory for plain and learning arrays as count + 1 elements. May be this is the point?
I'm allocating for count elements only.

**Comment by KaiserSozo** [comment] 2018-03-19 11:07
Checked with count+1 allocation. Result the same(

**Comment by KaiserSozo** [comment] 2018-03-19 11:14
Okey, I found the problem. My data is too big. With 
int xdim = 32, ydim = 32;
int examplesCount = 1024;
probem is not occured.

**Comment by KaiserSozo** [comment] 2018-03-19 11:20
I'm loading approximately 21 Mb of data. Is it too big?

**Comment by KaiserSozo** [comment] 2018-03-19 11:31
Run with int xdim = 5000, ydim =200;
                    int examplesCount = 100544;

**Comment by JeWaVe** [comment] 2018-03-19 12:36
Finally reproduced your issue. 
By doing new float[xdim], you allocate 20KB of memory per thread. In my case, I run this kernel with 16*28 *  128 threads, yielding ~1.1GB of memory allocated on heap. This by far exceeds the device default capacity. 

You can see than by activating null checks (I recommend to do so in DEBUG) : http://www.altimesh.com/automatic-null-checks/

Or by running cudaMemcheck. 


You will find a better explanation at https://stackoverflow.com/questions/17929054/understanding-cuda-heap-memory-limitations-per-thread

And a way to increase heap size here : http://horacio9573.no-ip.org/cuda/group__CUDART__DEVICE_gb8a22e29cc297634b0702db0b69f59e7.html

**Comment by JeWaVe** [comment] 2018-03-20 09:02
Ok I finally reproduced your issue and it's a valid issue. Today new T[] in device code looks broken. 

Here are two workarounds : 

- Map malloc/free yourself:

  ```
      [IntrinsicFunction("malloc")]
        static void* malloc(int size)
        {
            return (void*)Marshal.AllocHGlobal(size);
        }

        [IntrinsicFunction("free")]
        static void free(void* ptr)
        {
            Marshal.FreeHGlobal(new IntPtr(ptr));
        }

        [EntryPoint]
        public static void ComputeKohonen(float[] plainNetwork, float[] learningExamples, int xDim, int yDim, int examplesCount)
        {
            Parallel.For(0, examplesCount, (i) =>
            {
                float* output = (float*)malloc(xDim * sizeof(float));
                //float[] output = new float[xDim];
                
                for (int j = 0; j < xDim; j += 1)
                {
                    float sum = 0.0f;

                    for (int k = 0; k < yDim; ++k)
                    {
                        float difDist = plainNetwork[j * yDim + k] - learningExamples[i * yDim + k];
                        sum += difDist * difDist;
                    }

                    output[j] = (float) Math.Sqrt(sum);
                }

                free((void*)output);
            });
        }
```

Warning : all threads will perform malloc, this will be quite slow, and can lead to huge amount of per-thread allocated memory. 

- Allocate shared memory, using SharedMemoryAllocator


`                float[] output = new SharedMemoryAllocator<float>().allocate(xDim * sizeof(float));`

This will deliver much better performances, but requires an additional step : 
When you run your kernel, you must provide the amount of shared memory you will use, in that case
xDim * sizeof(float) * blockDim

**Comment by KaiserSozo** [comment] 2018-03-20 09:14
Ok, thanks in advance.
As I understand total shared memory for the block allocates here .SetDistrib(...int shared)?

**Comment by JeWaVe** [comment] 2018-03-20 09:15
yes exactly. 

for example 

`SetDistrib(16*prop.multiProcessorCount, 1, 128, 1, 1, xdim * sizeof(float) * 128)`

**Comment by KaiserSozo** [comment] 2018-03-20 09:17
Thank you!

**Comment by JeWaVe** [comment] 2018-03-20 09:39
You're very welcome. 
Thanks for reporting the issue, it should be fixed by next release.

**Comment by KaiserSozo** [comment] 2018-03-20 15:57
Unfortunately, shared memory maximum is 48 kb per block. And this is not suitable for me. Anyway I tried and got:
Memory Checker detected 1 access violations.
error = misaligned store (shared memory)
here: output[j] = (float) Math.Sqrt(sum);    (j = 0)
May it will help you too.
And I'm, in the meantime, going to use malloc.

**Comment by KaiserSozo** [comment] 2018-03-20 17:56
Using malloc leads to unspecified launch failure, while code is obvious...
I think there is some memory allocation problem in total.

**Comment by JeWaVe** [comment] 2018-04-04 12:55
Hi, do you free memory at the end of your code block? 

new float[] in kernels will be supported by next release

**Comment by JeWaVe** [comment] 2018-05-18 12:56
new float[] is now supported in our beta version. Could you please give a try? 

http://www.altimesh.com/download_msi/

**Comment by JeWaVe** [comment] 2018-05-24 07:45
fixed in https://marketplace.visualstudio.com/items?itemName=altimesh.AltimeshHybridizerExtensionEssentials

**Closed by JeWaVe** 2018-05-24 07:45 UTC
Labels: bug
