### ISSUE TITLE
ERROR IN RUNTIME INIT -- ABORTING EXECUTION

### ISSUE THREAD

**Issue by markosaviauk** [altimesh/hybridizer-basic-samples#36] opened 2018-02-01 07:48 UTC
Hi, 

The Hello world example gets the error "ERROR IN RUNTIME INIT -- ABORTING EXECUTION"

![image](https://user-images.githubusercontent.com/14886254/35666856-4e670bc4-0734-11e8-8178-f181a0322c86.png)

![image](https://user-images.githubusercontent.com/14886254/35666908-7caf2a34-0734-11e8-99ad-b48556f927c4.png)

Visual Studio 2017 version: 15.4.5.
Cuda 9.1 (newest toolkit)

What could cause the error?

**Comment by markosaviauk** [comment] 2018-02-01 08:10
I give the compilator output also as here are some warnings:
1>------ Rebuild All started: Project: ConsoleApp11, Configuration: Debug x64 ------
1>  ConsoleApp11 -> C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11\bin\x64\Debug\ConsoleApp11.exe
2>------ Rebuild All started: Project: ConsoleApp11_CUDA.vs2017, Configuration: Debug x64 ------
2>C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11_CUDA\ConsoleApp11_CUDA.vs2017.vcxproj(146,5): warning MSB4011: "C:\Users\marko\AppData\Local\Microsoft\VisualStudio\15.0_12ee2e74\Extensions\f0yoo4ky.ddp\vsintegration\Hybridizer.targets" cannot be imported again. It was already imported at "C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11_CUDA\ConsoleApp11_CUDA.vs2017.vcxproj (35,5)". This is most likely a build authoring error. This subsequent import will be ignored.
2>
2>C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11_CUDA>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe" -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile   -g   -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MDd " -o x64\Debug\hybridizer.wrappers.cu.obj "C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11_CUDA\hybridizer-generated-sources\hybridizer.wrappers.cu" -clean
2>hybridizer.wrappers.cu
2>Build satellite full path: C:\Users\marko\AppData\Local\Microsoft\VisualStudio\15.0_12ee2e74\Extensions\f0yoo4ky.ddp\bin\Hybridizer.VSIntegration.BuildSatellite.exe
2>Hybridizer binary full path: C:\Users\marko\AppData\Local\Microsoft\VisualStudio\15.0_12ee2e74\Extensions\f0yoo4ky.ddp\bin\Hybridizer.exe
2>Satellite working directory: C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11_CUDA\hybridizer-generated-sources
2>Builtins: C:\Users\marko\AppData\Local\Microsoft\VisualStudio\15.0_12ee2e74\Extensions\f0yoo4ky.ddp\include\hybridizer.cuda.builtins
2>Hybridizer out: [INFO] : entering BuildSatellite program
2>Hybridizer out: [INFO] : Loaded assembly from C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11\bin\x64\Debug\ConsoleApp11.exe
2>Hybridizer out: [WARNING] : EntryPoint attribute with empty or null name for method <Hello> in type <ConsoleApp11.Program>, using default symbols instead
2>Hybridizer out: [INFO] : Found type <ConsoleApp11.Program> with <1> methods
2>Hybridizer out: [INFO] : Done searching assembly for hybridizer directives
2>Hybridizer out: Hybridizer full path: C:\Users\marko\AppData\Local\Microsoft\VisualStudio\15.0_12ee2e74\Extensions\f0yoo4ky.ddp\bin\Hybridizer.exe
2>Hybridizer out: [INFO] : found type Altimesh.Hybridizer.Application.Program
2>Hybridizer out: [INFO] : found method Void Main(System.String[])
2>Hybridizer out: 2018/02/01 10:07:46:431 [INFO]  Hybridizer-BASIC (c) Altimesh 2011-2016 - 1.0.0.0
2>Hybridizer out: 2018/02/01 10:07:46:599 [INFO]  Hybridizer license: Trial version - for evaluation purpose only
2>Hybridizer out: 2018/02/01 10:07:46:851 [INFO]  Processing assembly C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11\bin\x64\Debug\ConsoleApp11.exe
2>Hybridizer out: 2018/02/01 10:07:46:869 [WARN]  WARNING : using default builtins
2>Hybridizer out: 2018/02/01 10:07:46:893 [INFO]  Loaded built-in configuration from C:\Users\marko\AppData\Local\Microsoft\VisualStudio\15.0_12ee2e74\Extensions\f0yoo4ky.ddp\include\hybridizer.cuda.builtins
2>Hybridizer out: 2018/02/01 10:07:46:893 [INFO]  Processing type ConsoleApp11.Program
2>Hybridizer out: 2018/02/01 10:07:46:939 [INFO]  Reading for method Void Hello() from assembly ConsoleApp11, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>Hybridizer out: 2018/02/01 10:07:47:010 [INFO]  Registering methods
2>Hybridizer out: 2018/02/01 10:07:47:018 [INFO]  Reading for method Void Hello() from assembly ConsoleApp11, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>Hybridizer out: 2018/02/01 10:07:47:020 [INFO]  Reading for method Void Hello() from assembly ConsoleApp11, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>Hybridizer out: 2018/02/01 10:07:47:048 [INFO]  Reading for method Void Hello() from assembly ConsoleApp11, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>Hybridizer out: 2018/02/01 10:07:47:165 [INFO]  Reading for method System.IO.TextWriter get_Out() from assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2>Hybridizer out: 2018/02/01 10:07:47:313 [INFO]  No symbols found for System.IO.TextWriter get_Out()
2>Hybridizer out: 2018/02/01 10:07:47:332 [INFO]  Reading for method Void Write(System.String) from assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2>Hybridizer out: 2018/02/01 10:07:47:332 [INFO]  No symbols found for Void Write(System.String)
2>Hybridizer out: 2018/02/01 10:07:47:335 [INFO]  Flavor CUDA has 3 methods
2>Hybridizer out: 2018/02/01 10:07:47:348 [INFO]  Flavor CUDA has 3 methods
2>Hybridizer out: 2018/02/01 10:07:47:369 [INFO]  Listing types found for flavor <CUDA>
2>Hybridizer out: 2018/02/01 10:07:47:369 [INFO]  found type <System.Object> used by :
2>Hybridizer out: 2018/02/01 10:07:47:369 [INFO]               <ConsoleApp11.Program>
2>Hybridizer out: 2018/02/01 10:07:47:369 [INFO]               <System.Console>
2>Hybridizer out: 2018/02/01 10:07:47:369 [INFO]  Done listing types found for flavor <CUDA>
2>Hybridizer out: Not Found Altimesh.Hybridizer.Application.resources, Version=1.0.0.0, Culture=et-EE, PublicKeyToken=null
2>Hybridizer out: Not Found Altimesh.Hybridizer.Application.resources, Version=1.0.0.0, Culture=et-EE, PublicKeyToken=null
2>Hybridizer out: Not Found Altimesh.Hybridizer.Application.resources, Version=1.0.0.0, Culture=et, PublicKeyToken=null
2>Hybridizer out: Not Found Altimesh.Hybridizer.Application.resources, Version=1.0.0.0, Culture=et, PublicKeyToken=null
2>Hybridizer out: Not Found mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2>Hybridizer out: Not Found Altimesh.Hybridizer.Application.resources, Version=1.0.0.0, Culture=et-EE, PublicKeyToken=null
2>Hybridizer out: Not Found Altimesh.Hybridizer.Application.resources, Version=1.0.0.0, Culture=et-EE, PublicKeyToken=null
2>Hybridizer out: Not Found Altimesh.Hybridizer.Application.resources, Version=1.0.0.0, Culture=et, PublicKeyToken=null
2>Hybridizer out: Not Found Altimesh.Hybridizer.Application.resources, Version=1.0.0.0, Culture=et, PublicKeyToken=null
2>Hybridizer out: [INFO] : PTXJitter called <"C:\Users\marko\AppData\Local\Microsoft\VisualStudio\15.0_12ee2e74\Extensions\f0yoo4ky.ddp\bin\Hybridizer.PTXJitterService.9.1.exe" 00000000000005A0 0000000000000580>
2>Hybridizer out: [INFO] : Fini Void Main(System.String[])
2>Hybridizer out: [DONE]
2>C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11_CUDA\ConsoleApp11_CUDA.vs2017.vcxproj(146,5): warning MSB4011: "C:\Users\marko\AppData\Local\Microsoft\VisualStudio\15.0_12ee2e74\Extensions\f0yoo4ky.ddp\vsintegration\Hybridizer.targets" cannot be imported again. It was already imported at "C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11_CUDA\ConsoleApp11_CUDA.vs2017.vcxproj (35,5)". This is most likely a build authoring error. This subsequent import will be ignored.
2>Compiling CUDA source file hybridizer-generated-sources\hybridizer.wrappers.cu...
2>
2>C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11_CUDA>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" --use-local-env --cl-version 2017 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static  -g   -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MDd " -o x64\Debug\hybridizer.wrappers.cu.obj "C:\Users\marko\source\repos\ConsoleApp11\ConsoleApp11_CUDA\hybridizer-generated-sources\hybridizer.wrappers.cu"
2>c:\program files\nvidia gpu computing toolkit\cuda\v9.1\include\crt/device_functions.h : warning C4819: The file contains a character that cannot be represented in the current code page (1257). Save the file in Unicode format to prevent data loss
2>c:\program files\nvidia gpu computing toolkit\cuda\v9.1\include\crt/device_functions.h : warning C4819: The file contains a character that cannot be represented in the current code page (1257). Save the file in Unicode format to prevent data loss
2>hybridizer.wrappers.cu
2>Done building project "ConsoleApp11_CUDA.vs2017.vcxproj".
2>hybridizer.generated.cpp
2>   Creating library C:\Users\marko\source\repos\ConsoleApp11\x64\Debug\ConsoleApp11_CUDA.vs2017.lib and object C:\Users\marko\source\repos\ConsoleApp11\x64\Debug\ConsoleApp11_CUDA.vs2017.exp
2>ConsoleApp11_CUDA.vs2017.vcxproj -> C:\Users\marko\source\repos\ConsoleApp11\x64\Debug\ConsoleApp11_CUDA.vs2017.dll
2>copy "C:\Users\marko\AppData\Local\Microsoft\VisualStudio\15.0_12ee2e74\Extensions\f0yoo4ky.ddp\bin\hybridizer.basic.runtime.dll" "C:\Users\marko\source\repos\ConsoleApp11\x64\Debug\"
2>        1 file(s) copied.
2>Done building project "ConsoleApp11_CUDA.vs2017.vcxproj".
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Comment by JeWaVe** [comment] 2018-02-01 08:18
Hi, 

This error is usually fired if you build and run the generated code on two different machines. 
You can request a new license for the runtime machine and compile code on it.

**Comment by markosaviauk** [comment] 2018-02-01 10:01
Thanks for the quick response.

I use only one machine. But at the first I used latest Visual Studio 15.6... and installed the hybridizer to it. Then I removed the Visual studio and installed the older version 15.4.5. And the hybridized was/is already licenced. And there is not possible to renew the licence. If I click to the "Reset" button the dialog window will close automatically (I assume some internal error).

![image](https://user-images.githubusercontent.com/14886254/35672444-4c92c12c-0747-11e8-88af-4ec952cbe40a.png)

**Comment by JeWaVe** [comment] 2018-02-01 10:09
I repro the reset button failure. 
Working on a fix

**Comment by JeWaVe** [comment] 2018-02-01 10:19
could you send me an email to regis dot portalez at altimesh dot com, so that I can send you a fixed version without affecting others users?

**Comment by markosaviauk** [comment] 2018-02-01 10:41
My email is marko.saviauk@mail.ee <mailto:marko.saviauk@mail.ee> 

 

Marko Saviauk

**Comment by JeWaVe** [comment] 2018-02-01 10:59
This looks related to win32/x64. 
Could you specify Windows version and if it's a 32 or 64 bits version? 

Thanks

**Comment by markosaviauk** [comment] 2018-02-01 11:06
Win10 Home 64bit, the screenshot:
![image](https://user-images.githubusercontent.com/14886254/35675424-a0143fca-0750-11e8-93d5-50242c092794.png)

**Comment by markosaviauk** [comment] 2018-02-01 11:09
![image](https://user-images.githubusercontent.com/14886254/35675566-1dc14a76-0751-11e8-9245-73118dc764b6.png)

**Comment by JeWaVe** [comment] 2018-02-01 15:06
Could you please try to repair your visual studio installation?

**Comment by markosaviauk** [comment] 2018-02-01 15:22
I repaired the Visual Studio. The extensions lost nicely. Installed the hybridizer. But the licence information appeared again and not possible to reset it.

**Comment by JeWaVe** [comment] 2018-02-12 15:42
cannot reproduce

**Comment by JeWaVe** [comment] 2018-02-14 08:02
Reproduced, should be fixed in next release

**Comment by JeWaVe** [comment] 2018-02-15 15:40
should be fixed in https://marketplace.visualstudio.com/items?itemName=altimesh.AltimeshHybridizerExtensionEssentials v 8707

**Closed by JeWaVe** 2018-02-15 15:40 UTC
Labels: bug
