### ISSUE TITLE
VS2019, does it support it? Hybridizer menu missing after I installed it.

### ISSUE THREAD

**Issue by hsdxpro** [altimesh/hybridizer-basic-samples#85] opened 2019-07-15 14:01 UTC
Title

**Comment by JeWaVe** [comment] 2019-07-15 14:49
Hi, 

yes we do support VS2019. But extension menu has moved. 

it's now in Extensions-> Hybridizer

**Comment by hsdxpro** [comment] 2019-07-15 17:29
Hi @JeWaVe 

Thank you for the really fast answer!
I have a fresh installation of VS2019 on win10, it's installed into F:, not my C: system drive that could be an issue? 

I can't find Hybridizer project templates, and also when I search in the Extensions there is no sign of Hybridizer. Any ideas? I used this link to download Hybridizer: https://marketplace.visualstudio.com/items?itemName=altimesh.AltimeshHybridizerExtensionEssentials

**Comment by andrewsil1** [comment] 2019-07-26 18:21
I just tried installing it from the Marketplace web site.  There is nothing in the extensions menu in VS2019 afterwards even though no errors were shown during installation.  Kind of at a loss as to how to get started.  All the files seem to be in \program files\altimesh\... but nothing seems to have been copied to the VS installation.

**Comment by andrewsil1** [comment] 2019-07-26 18:24
So you have to manually launch the VSIX installer after going through the MSI installation?  Seems like that's what I had to do.

**Comment by AbdelAzizAbdelLatef** [comment] 2019-08-07 19:44
@andrewsil1 I have the same problem. How can I manually launch the VSIX installer?

**Comment by andrewsil1** [comment] 2019-08-07 20:30
Double click the MSI file in the directory the package was installed to.

Andy Silverman
Microsoft AIAA, Azure Hardware Systems Group

Written using Outlook<https://aka.ms/qtex0l> for iOS
Big thumbs, small keyboard — excuse typos.
________________________________

**Comment by AbdelAzizAbdelLatef** [comment] 2019-08-07 22:37
I have already done this before and get a message saying it was successfully installed, but the extension didn't show up.

**Comment by JeWaVe** [comment] 2019-08-08 08:25
In visual 2019, microsoft change the extension menu appearance. 
They are now in Extensions->Hybridizer

**Comment by AbdelAzizAbdelLatef** [comment] 2019-08-08 10:45
I already know that it should be in Extensions->Hybridizer, but it is not there,
![Ext](https://user-images.githubusercontent.com/53878132/62697172-bdfe2980-b99f-11e9-936d-75990c8bebb3.png)
![Installation](https://user-images.githubusercontent.com/53878132/62697173-be96c000-b99f-11e9-940e-029d9a07e9c6.JPG)

**Comment by JeWaVe** [comment] 2019-08-09 09:18
Apparently VS2019 changed something in their project templates management. 
We didn't catch it. 
Sorry for the inconvenience

**Comment by AbdelAzizAbdelLatef** [comment] 2019-08-09 16:46
Please help us to solve this issue quickly. I need Hybridizer as soon as possible.

**Comment by JeWaVe** [comment] 2019-08-29 15:58
We just published a new release. Could you confirm the issue is solved? 
I cannot reproduce on my environment (latest VS and windows)

**Comment by JeWaVe** [comment] 2019-08-30 08:58
Identified the issue; 
When you have visual studio 2019 only, automatic vsix installation doesn't start. 
You can manually install it by clicking the vsix from
[Program Files]\Altimesh\Hybridizer Essentials

**Comment by AbdelAzizAbdelLatef** [comment] 2019-09-01 05:01
I downloaded the latest version, but I had to start it manually by clicking the vsix from
[Program Files]\Altimesh\Hybridizer Essentials.

**Comment by JeWaVe** [comment] 2019-09-04 07:52
fix is ready and implemented. 
Issue is that one : https://stackoverflow.com/questions/30504/programmatically-retrieve-visual-studio-install-directory

(vs 2017 and 2019 don't write their install directory in windows registries)

**Comment by JeWaVe** [comment] 2019-09-05 14:45
should be fixed by latest release (1.2.10616)

**Closed by JeWaVe** 2019-09-05 14:45 UTC
Labels: Installer, bug
